<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2014.2.1.284
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Отправка Форма Форма',
	'heading' => 'Отправка новой формы',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Отмечено',
		'checkbox_unchecked' => 'Флажок не установлен',
		'submitted_from' => 'Формы, отправленные с веб-сайта: %s',
		'submitted_by' => 'IP-адрес посетителя: %s',
		'too_many_submissions' => 'Недопустимо высокое количество отправок с этого IP-адреса за последнее время',
		'failed_to_send_email' => 'Не удалось отправить сообщение эл. почты',
		'invalid_reCAPTCHA_private_key' => 'Недействительный закрытый ключ reCAPTCHA.',
		'invalid_field_type' => 'Неизвестный тип поля \'%s\'.',
		'unknown_method' => 'Неизвестный метод запроса сервера'
	),
	'email' => array(
		'from' => '',
		'to' => ''
	),
	'fields' => array(
		'custom_U1968' => array(
			'type' => 'string',
			'label' => 'Ваше имя',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Ваше имя\' не может быть пустым.'
			)
		),
		'Email' => array(
			'type' => 'email',
			'label' => 'Электронная почта',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Электронная почта\' не может быть пустым.',
				'format' => 'Поле \'Электронная почта\' содержит недействительное сообщение эл. почты.'
			)
		),
		'custom_U1962' => array(
			'type' => 'string',
			'label' => 'Адрес доставки',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U2021' => array(
			'type' => 'string',
			'label' => 'Сообщение',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Сообщение\' не может быть пустым.'
			)
		),
		'custom_U2115' => array(
			'type' => 'checkbox',
			'label' => 'Камера моего смартфона имеет увеличение 8МПикс или более',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Камера моего смартфона имеет увеличение 8МПикс или более\' не может быть пустым.'
			)
		)
	)
);

process_form($form);
?>
